/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const AIPlan = IDL.Record({
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'generatedAt' : IDL.Int,
  'planType' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
});
export const DailyCheckIn = IDL.Record({
  'waterGlasses' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'dietFollowed' : IDL.Bool,
  'steps' : IDL.Nat,
  'workoutDone' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'activityLevel' : IDL.Text,
  'fitnessGoal' : IDL.Text,
  'heightCm' : IDL.Float64,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'darkMode' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const Exercise = IDL.Record({
  'id' : IDL.Text,
  'difficulty' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArg = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addExercise' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'clearChatHistory' : IDL.Func([], [], []),
  'deleteExercise' : IDL.Func([IDL.Text], [Result], []),
  'generateAIResponse' : IDL.Func([IDL.Text], [Result], []),
  'generateDietPlan' : IDL.Func([], [Result], []),
  'generateWorkoutPlan' : IDL.Func([], [Result], []),
  'getAIPlan' : IDL.Func([IDL.Text], [IDL.Opt(AIPlan)], ['query']),
  'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getCheckIns' : IDL.Func([IDL.Nat], [IDL.Vec(DailyCheckIn)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getWeightHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WeightEntry)], ['query']),
  'hasGeminiApiKey' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [Result], []),
  'saveAIPlan' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCheckIn' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Nat, IDL.Nat],
      [Result],
      [],
    ),
  'saveProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [Result],
      [],
    ),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'transformResponse' : IDL.Func(
      [TransformArg],
      [HttpRequestResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const AIPlan = IDL.Record({
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'generatedAt' : IDL.Int,
    'planType' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
  });
  const DailyCheckIn = IDL.Record({
    'waterGlasses' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'dietFollowed' : IDL.Bool,
    'steps' : IDL.Nat,
    'workoutDone' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'activityLevel' : IDL.Text,
    'fitnessGoal' : IDL.Text,
    'heightCm' : IDL.Float64,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'darkMode' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Text,
  });
  const WeightEntry = IDL.Record({
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Text,
    'difficulty' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArg = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addExercise' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'clearChatHistory' : IDL.Func([], [], []),
    'deleteExercise' : IDL.Func([IDL.Text], [Result], []),
    'generateAIResponse' : IDL.Func([IDL.Text], [Result], []),
    'generateDietPlan' : IDL.Func([], [Result], []),
    'generateWorkoutPlan' : IDL.Func([], [Result], []),
    'getAIPlan' : IDL.Func([IDL.Text], [IDL.Opt(AIPlan)], ['query']),
    'getChatHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getCheckIns' : IDL.Func([IDL.Nat], [IDL.Vec(DailyCheckIn)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getWeightHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WeightEntry)], ['query']),
    'hasGeminiApiKey' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [Result], []),
    'saveAIPlan' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCheckIn' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Nat, IDL.Nat],
        [Result],
        [],
      ),
    'saveProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [Result],
        [],
      ),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'transformResponse' : IDL.Func(
        [TransformArg],
        [HttpRequestResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };