/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIPlan {
  'content' : string,
  'userId' : Principal,
  'generatedAt' : bigint,
  'planType' : string,
}
export interface ChatMessage {
  'id' : string,
  'content' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'role' : string,
}
export interface DailyCheckIn {
  'waterGlasses' : bigint,
  'userId' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'dietFollowed' : boolean,
  'steps' : bigint,
  'workoutDone' : boolean,
}
export interface Exercise {
  'id' : string,
  'difficulty' : bigint,
  'name' : string,
  'createdBy' : [] | [Principal],
  'description' : string,
  'muscleGroup' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface TransformArg {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface UserProfile {
  'age' : bigint,
  'activityLevel' : string,
  'fitnessGoal' : string,
  'heightCm' : number,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'darkMode' : boolean,
  'updatedAt' : bigint,
  'weightKg' : number,
  'gender' : string,
}
export interface WeightEntry {
  'userId' : Principal,
  'date' : string,
  'weightKg' : number,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addExercise' : ActorMethod<[string, string, string, bigint, string], Result>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'deleteExercise' : ActorMethod<[string], Result>,
  'generateAIResponse' : ActorMethod<[string], Result>,
  'generateDietPlan' : ActorMethod<[], Result>,
  'generateWorkoutPlan' : ActorMethod<[], Result>,
  'getAIPlan' : ActorMethod<[string], [] | [AIPlan]>,
  'getChatHistory' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getCheckIns' : ActorMethod<[bigint], Array<DailyCheckIn>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStreak' : ActorMethod<[], bigint>,
  'getWeightHistory' : ActorMethod<[bigint], Array<WeightEntry>>,
  'hasGeminiApiKey' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listExercises' : ActorMethod<[], Array<Exercise>>,
  'logWeight' : ActorMethod<[string, number], Result>,
  'saveAIPlan' : ActorMethod<[string, string], Result>,
  'saveChatMessage' : ActorMethod<[string, string], string>,
  'saveCheckIn' : ActorMethod<
    [string, boolean, boolean, bigint, bigint],
    Result
  >,
  'saveProfile' : ActorMethod<
    [string, bigint, string, number, number, string, string, boolean],
    Result
  >,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'transformResponse' : ActorMethod<[TransformArg], HttpRequestResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];