/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: string;
    difficulty: bigint;
    name: string;
    createdBy?: Principal;
    description: string;
    muscleGroup: string;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface TransformArg {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface DailyCheckIn {
    waterGlasses: bigint;
    userId: Principal;
    date: string;
    createdAt: bigint;
    dietFollowed: boolean;
    steps: bigint;
    workoutDone: boolean;
}
export interface AIPlan {
    content: string;
    userId: Principal;
    generatedAt: bigint;
    planType: string;
}
export interface ChatMessage {
    id: string;
    content: string;
    userId: Principal;
    createdAt: bigint;
    role: string;
}
export interface WeightEntry {
    userId: Principal;
    date: string;
    weightKg: number;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface UserProfile {
    age: bigint;
    activityLevel: string;
    fitnessGoal: string;
    heightCm: number;
    userId: Principal;
    name: string;
    createdAt: bigint;
    darkMode: boolean;
    updatedAt: bigint;
    weightKg: number;
    gender: string;
}
export interface backendInterface {
    addAdmin(newAdmin: Principal): Promise<void>;
    addExercise(id: string, name: string, muscleGroup: string, difficulty: bigint, description: string): Promise<Result>;
    clearChatHistory(): Promise<void>;
    deleteExercise(id: string): Promise<Result>;
    generateAIResponse(userMessage: string): Promise<Result>;
    generateDietPlan(): Promise<Result>;
    generateWorkoutPlan(): Promise<Result>;
    getAIPlan(planType: string): Promise<AIPlan | null>;
    getChatHistory(limit: bigint): Promise<Array<ChatMessage>>;
    getCheckIns(limit: bigint): Promise<Array<DailyCheckIn>>;
    getProfile(): Promise<UserProfile | null>;
    getStreak(): Promise<bigint>;
    getWeightHistory(limit: bigint): Promise<Array<WeightEntry>>;
    hasGeminiApiKey(): Promise<boolean>;
    isAdmin(): Promise<boolean>;
    listExercises(): Promise<Array<Exercise>>;
    logWeight(date: string, weightKg: number): Promise<Result>;
    saveAIPlan(planType: string, content: string): Promise<Result>;
    saveChatMessage(role: string, content: string): Promise<string>;
    saveCheckIn(date: string, workoutDone: boolean, dietFollowed: boolean, waterGlasses: bigint, steps: bigint): Promise<Result>;
    saveProfile(name: string, age: bigint, gender: string, heightCm: number, weightKg: number, fitnessGoal: string, activityLevel: string, darkMode: boolean): Promise<Result>;
    setGeminiApiKey(key: string): Promise<void>;
    transformResponse(arg: TransformArg): Promise<HttpRequestResult>;
}
import type { AIPlan as _AIPlan, Exercise as _Exercise, Result as _Result, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addExercise(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async deleteExercise(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateAIResponse(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAIResponse(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAIResponse(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateDietPlan(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDietPlan();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDietPlan();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateWorkoutPlan(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWorkoutPlan();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWorkoutPlan();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAIPlan(arg0: string): Promise<AIPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIPlan(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIPlan(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return result;
        }
    }
    async getCheckIns(arg0: bigint): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckIns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckIns(arg0);
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreak();
            return result;
        }
    }
    async getWeightHistory(arg0: bigint): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightHistory(arg0);
            return result;
        }
    }
    async hasGeminiApiKey(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasGeminiApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasGeminiApiKey();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExercises();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExercises();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async logWeight(arg0: string, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.logWeight(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWeight(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAIPlan(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAIPlan(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAIPlan(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveChatMessage(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChatMessage(arg0, arg1);
            return result;
        }
    }
    async saveCheckIn(arg0: string, arg1: boolean, arg2: boolean, arg3: bigint, arg4: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCheckIn(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCheckIn(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProfile(arg0: string, arg1: bigint, arg2: string, arg3: number, arg4: number, arg5: string, arg6: string, arg7: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGeminiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGeminiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGeminiApiKey(arg0);
            return result;
        }
    }
    async transformResponse(arg0: TransformArg): Promise<HttpRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transformResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformResponse(arg0);
            return result;
        }
    }
}
function from_candid_Exercise_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIPlan]): AIPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    difficulty: bigint;
    name: string;
    createdBy: [] | [Principal];
    description: string;
    muscleGroup: string;
}): {
    id: string;
    difficulty: bigint;
    name: string;
    createdBy?: Principal;
    description: string;
    muscleGroup: string;
} {
    return {
        id: value.id,
        difficulty: value.difficulty,
        name: value.name,
        createdBy: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.createdBy)),
        description: value.description,
        muscleGroup: value.muscleGroup
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
